name: html_components
version: 0.1.5
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library written in HTML and Dart using Polymer.dart.
homepage: https://github.com/szgabsz91/html-components
dependencies:
  animation: 0.5.21
  polymer: 0.9.3+2
  unittest: 0.9.2+1
transformers:
- polymer:
    entry_points: []
