name: html_components
version: 0.1.2
author: Gabor Szabo <szgabsz91@gmail.com>
description: A reusable component library written in HTML and Dart using Polymer.dart.
homepage: https://github.com/szgabsz91/html-components
dependencies:
  animation: any
  polymer: any
  unittest: any
transformers:
- polymer:
    entry_points: []